version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - wget https://releases.hashicorp.com/terraform/0.10.4/terraform_0.10.4_linux_amd64.zip
      - unzip terraform_0.10.4_linux_amd64.zip
      - sudo mv terraform /bin
      - cd terraform
      - terraform init
      - terraform plan
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
