version: 0.2

run-as: root

phases:
  install:
    commands:
      - cd /usr/bin
      - curl -s -qL o terraform.zip https://releases.hashicorp.com/terraform/0.10.4/terraform_0.10.4_linux_amd64.zip
      - unzip -o terraform.zip
  build:
    commands:
      - echo Build started on `date`
      - cd $CODEBUILD_SRC_DIR
      - pwd
      - terraform init -input=false -backend-config="bucket=new-tc-terraform-state"
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - '*/*'