version: 0.2

phases:
  pre_build:
    commands:
      # Descargar e instalar la versión de Terraform especificada en la fase install
      - curl -O https://releases.hashicorp.com/terraform/1.0.9/terraform_1.0.9_linux_amd64.zip
      - unzip terraform_1.0.9_linux_amd64.zip
      - which date
      - mv terraform /usr/local/bin/
      - echo "Running Terraform commands..."
      - cd codeterraform
      - terraform init -input=false -backend-config="bucket=new-tc-terraform-state"

  build:
    commands:
      echo "Applying Terraform changes..."
      terraform plan

  post_build:
    commands:
      echo "Build complete"


